#!/usr/bin/env python
import argparse
from langdet import RandomLanguageDetector, stream_sample


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('train', help='Training set')
    parser.add_argument('test', help='Testing set')
    args = parser.parse_args()

    det = RandomLanguageDetector()
    det.train(stream_sample(args.train))
    precision, recall, mistakes = det.eval(stream_sample(args.test))

    print '%s\t%s\t%s' % ('Lang', 'Prec', 'Rec')
    for lang in sorted(precision):
        print '%s\t%.2f\t%.2f' % (lang, precision[lang], recall[lang])
